"""Site and Group Tables

Revision ID: a867097dafa8
Revises: 
Create Date: 2025-07-23 13:43:08.982771

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a867097dafa8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
