"""Update Site Table

Revision ID: 73e0381bc79b
Revises: 38f23ba5bc76
Create Date: 2025-07-23 14:36:30.033011

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "73e0381bc79b"
down_revision: str | None = "38f23ba5bc76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
