"""Update Group Table

Revision ID: 38f23ba5bc76
Revises: 54c8a6ebace3
Create Date: 2025-07-23 14:04:55.597532

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "38f23ba5bc76"
down_revision: str | None = "54c8a6ebace3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
